export { default as Usuarios } from './pages/Usuarios.jsx'
export { default as Configuracion } from './pages/Configuracion.jsx'
export { Empresas } from './pages/Empresas.jsx'
export { Sucursales } from './pages/Sucursales.jsx'
export { Modulos } from './pages/Modulos.jsx'
export { Almacenes } from './pages/Almacenes.jsx'
export { default as Roles } from './pages/Roles.jsx'
